# Development Compose File
version: '3'
services:
  app:
    image: node:12
    environment: 
    - NODE_ENV=development
    working_dir: /usr/src/app
    command: npm run start:dev
    ports:
      - 3000:3000
      - 9229:9229
    volumes: 
      - .:/usr/src/app
networks: 
  default:
    driver: bridge
